// examples/chat-vue/src/App.vue
<script setup lang="ts">
import { SukkoClient } from "@sukko/sdk";
import { WebSocketTransport } from "@sukko/websocket";
import { ref, shallowRef } from "vue";
import type { ChatMessage } from "./utils";

const wsUrl = ref("ws://localhost:3000/ws");
const token = ref("");
const client = shallowRef<SukkoClient | null>(null);
const messages = ref<ChatMessage[]>([]);
const _selectedChannel = ref<string | null>(null);

function addMessage(msg: ChatMessage) {
	messages.value = [...messages.value, msg].slice(-200);
}

function handleConnect() {
	if (client.value) {
		client.value.disconnect();
	}

	const transport = new WebSocketTransport({ url: wsUrl.value });
	const newClient = new SukkoClient({
		transport,
		token: token.value,
		autoConnect: false,
		reconnect: true,
	});

	client.value = newClient;
	newClient.connect();
}

function handleDisconnect() {
	if (client.value) {
		client.value.disconnect();
		client.value = null;
	}
}
</script>

<template>
	<SukkoProvider v-if="client" :client="client">
		<ConnectionPanel
			:ws-url="wsUrl"
			:token="token"
			:connected="true"
			@update:ws-url="wsUrl = $event"
			@update:token="token = $event"
			@connect="handleConnect"
			@disconnect="handleDisconnect"
		/>
		<div class="main-layout">
			<ChannelSidebar
				:token="token"
				:selected-channel="selectedChannel"
				@select-channel="selectedChannel = $event"
				@message="addMessage"
			/>
			<div class="message-feed">
				<MessageFeed :messages="messages" @message="addMessage" />
				<MessageInput
					:token="token"
					:selected-channel="selectedChannel"
					@message="addMessage"
				/>
			</div>
		</div>
	</SukkoProvider>
	<template v-else>
		<ConnectionPanel
			:ws-url="wsUrl"
			:token="token"
			:connected="false"
			@update:ws-url="wsUrl = $event"
			@update:token="token = $event"
			@connect="handleConnect"
			@disconnect="handleDisconnect"
		/>
		<div class="main-layout">
			<div style="flex: 1; display: flex; align-items: center; justify-content: center; color: #8b949e">
				Enter a WebSocket URL and token, then click Connect.
			</div>
		</div>
	</template>
</template>

// examples/chat-react/src/components/App.tsx
import { SukkoProvider } from "@sukko/react";
import { SukkoClient } from "@sukko/sdk";
import { WebSocketTransport } from "@sukko/websocket";
import { useCallback, useRef, useState } from "react";
import type { ChatMessage } from "../utils";
import { ChannelSidebar } from "./ChannelSidebar";
import { ConnectionPanel } from "./ConnectionPanel";
import { MessageFeed } from "./MessageFeed";
import { MessageInput } from "./MessageInput";

export function App() {
	const [client, setClient] = useState<SukkoClient | null>(null);
	const [messages, setMessages] = useState<ChatMessage[]>([]);
	const [selectedChannel, setSelectedChannel] = useState<string | null>(null);
	const [token, setToken] = useState("");
	const [wsUrl, setWsUrl] = useState("ws://localhost:3000/ws");
	const clientRef = useRef<SukkoClient | null>(null);

	const addMessage = useCallback((msg: ChatMessage) => {
		setMessages((prev) => {
			const next = [...prev, msg];
			return next.length > 200 ? next.slice(-200) : next;
		});
	}, []);

	const handleConnect = useCallback(() => {
		if (clientRef.current) {
			clientRef.current.disconnect();
		}

		const transport = new WebSocketTransport({ url: wsUrl });
		const newClient = new SukkoClient({
			transport,
			token,
			autoConnect: false,
			reconnect: true,
		});

		clientRef.current = newClient;
		setClient(newClient);
		newClient.connect();
	}, [wsUrl, token]);

	const handleDisconnect = useCallback(() => {
		if (clientRef.current) {
			clientRef.current.disconnect();
			clientRef.current = null;
			setClient(null);
		}
	}, []);

	const connectionPanel = (
		<ConnectionPanel
			wsUrl={wsUrl}
			token={token}
			connected={!!client}
			onWsUrlChange={setWsUrl}
			onTokenChange={setToken}
			onConnect={handleConnect}
			onDisconnect={handleDisconnect}
		/>
	);

	if (client) {
		return (
			<SukkoProvider client={client}>
				{connectionPanel}
				<div className="main-layout">
					<ChannelSidebar
						token={token}
						selectedChannel={selectedChannel}
						onSelectChannel={setSelectedChannel}
						onMessage={addMessage}
					/>
					<div className="message-feed">
						<MessageFeed messages={messages} onMessage={addMessage} />
						<MessageInput token={token} selectedChannel={selectedChannel} onMessage={addMessage} />
					</div>
				</div>
			</SukkoProvider>
		);
	}

	return (
		<>
			{connectionPanel}
			<div className="main-layout">
				<div
					style={{
						flex: 1,
						display: "flex",
						alignItems: "center",
						justifyContent: "center",
						color: "#8b949e",
					}}
				>
					Enter a WebSocket URL and token, then click Connect.
				</div>
			</div>
		</>
	);
}
