// examples/chat-vue/src/components/ChannelSidebar.vue
<script setup lang="ts">
import { useSubscription, useSukkoClient } from "@sukko/vue";
import { computed, ref, watch } from "vue";
import type { ChatMessage } from "../utils";
import { createMessageId, decodeTokenPayload } from "../utils";

const props = defineProps<{
	token: string;
	selectedChannel: string | null;
}>();

const emit = defineEmits<{
	selectChannel: [channel: string];
	message: [msg: ChatMessage];
}>();

const client = useSukkoClient();
const claims = computed(() => decodeTokenPayload(props.token));

const publicChannels = ["all.trade"];
const userChannels = computed(() =>
	claims.value.sub ? [`notifications.${claims.value.sub}`] : [],
);
const availableGroups = computed(() => claims.value.groups ?? []);
const joinedGroups = ref<string[]>([]);
const groupChannels = computed(() => joinedGroups.value.map((g) => `community.${g}`));

const allSubscribed = computed(() => [
	...publicChannels,
	...userChannels.value,
	...groupChannels.value,
]);

// Subscribe to all active channels
const { lastMessage } = useSubscription<Record<string, unknown>>({
	channels: allSubscribed,
	onMessage: (msg) => {
		const d = msg.data as Record<string, unknown>;
		emit("message", {
			id: createMessageId(),
			channel: msg.channel,
			sender: (d.sender as string) ?? "unknown",
			text: (d.text as string) ?? JSON.stringify(d),
			ts: msg.ts,
			type: "user",
		});
	},
});

// Auto-select first channel
watch(allSubscribed, (channels) => {
	if (!props.selectedChannel && channels.length > 0) {
		emit("selectChannel", channels[0]);
	}
}, { immediate: true });

function joinGroup(group: string) {
	if (!joinedGroups.value.includes(group)) {
		joinedGroups.value = [...joinedGroups.value, group];
	}
}

function leaveGroup(group: string) {
	const channel = `community.${group}`;
	client.unsubscribe([channel]);
	joinedGroups.value = joinedGroups.value.filter((g) => g !== group);
	if (props.selectedChannel === channel) {
		emit("selectChannel", allSubscribed.value[0] ?? "");
	}
}
</script>

<template>
	<div class="channel-sidebar">
		<div class="channel-section">
			<div class="channel-section-title">Public</div>
			<div
				v-for="ch in publicChannels"
				:key="ch"
				:class="['channel-item', { active: selectedChannel === ch }]"
				@click="emit('selectChannel', ch)"
			>
				<span class="channel-name">{{ ch }}</span>
			</div>
		</div>

		<div v-if="userChannels.length > 0" class="channel-section">
			<div class="channel-section-title">User</div>
			<div
				v-for="ch in userChannels"
				:key="ch"
				:class="['channel-item', { active: selectedChannel === ch }]"
				@click="emit('selectChannel', ch)"
			>
				<span class="channel-name">{{ ch }}</span>
			</div>
		</div>

		<div class="channel-section">
			<div class="channel-section-title">Groups</div>
			<div v-for="group in availableGroups" :key="group">
				<div v-if="joinedGroups.includes(group)"
					:class="['channel-item', { active: selectedChannel === `community.${group}` }]"
				>
					<span class="channel-name" @click="emit('selectChannel', `community.${group}`)">
						community.{{ group }}
					</span>
					<button @click="leaveGroup(group)">Leave</button>
				</div>
				<div v-else class="channel-item">
					<span class="channel-name" style="color: #8b949e">community.{{ group }}</span>
					<button @click="joinGroup(group)">Join</button>
				</div>
			</div>
		</div>
	</div>
</template>

// examples/chat-react/src/components/ChannelSidebar.tsx
import { useSubscription, useSukkoClient } from "@sukko/react";
import { useEffect, useMemo, useState } from "react";
import type { ChatMessage } from "../utils";
import { createMessageId, decodeTokenPayload } from "../utils";

function SubscribedChannel(props: {
	channel: string;
	active: boolean;
	onSelect: () => void;
	onMessage: (msg: ChatMessage) => void;
	action?: { label: string; onClick: () => void };
}) {
	useSubscription<Record<string, unknown>>({
		channels: [props.channel],
		onMessage: (msg) => {
			const d = msg.data as Record<string, unknown>;
			props.onMessage({
				id: createMessageId(),
				channel: msg.channel,
				sender: (d.sender as string) ?? "unknown",
				text: (d.text as string) ?? JSON.stringify(d),
				ts: msg.ts,
				type: "user",
			});
		},
	});

	return (
		<div
			className={`channel-item ${props.active ? "active" : ""}`}
			onClick={props.onSelect}
			onKeyDown={(e) => e.key === "Enter" && props.onSelect()}
		>
			<span className="channel-name">{props.channel}</span>
			{props.action && (
				<button
					type="button"
					onClick={(e) => {
						e.stopPropagation();
						props.action!.onClick();
					}}
				>
					{props.action.label}
				</button>
			)}
		</div>
	);
}

export function ChannelSidebar(props: {
	token: string;
	selectedChannel: string | null;
	onSelectChannel: (channel: string) => void;
	onMessage: (msg: ChatMessage) => void;
}) {
	const client = useSukkoClient();
	const claims = useMemo(() => decodeTokenPayload(props.token), [props.token]);

	const publicChannels = useMemo(() => ["all.trade"], []);
	const userChannels = useMemo(
		() => (claims.sub ? [`notifications.${claims.sub}`] : []),
		[claims.sub],
	);
	const availableGroups = claims.groups ?? [];
	const [joinedGroups, setJoinedGroups] = useState<string[]>([]);

	const allSubscribed = useMemo(
		() => [...publicChannels, ...userChannels, ...joinedGroups.map((g) => `community.${g}`)],
		[publicChannels, userChannels, joinedGroups],
	);

	// Auto-select first channel
	useEffect(() => {
		if (!props.selectedChannel && allSubscribed.length > 0) {
			props.onSelectChannel(allSubscribed[0]);
		}
	}, [props.selectedChannel, props.onSelectChannel, allSubscribed]);

	const handleJoinGroup = (group: string) => {
		if (!joinedGroups.includes(group)) {
			setJoinedGroups((prev) => [...prev, group]);
		}
	};

	const handleLeaveGroup = (group: string) => {
		const channel = `community.${group}`;
		client.unsubscribe([channel]);
		setJoinedGroups((prev) => prev.filter((g) => g !== group));
		if (props.selectedChannel === channel) {
			props.onSelectChannel(allSubscribed[0] ?? "");
		}
	};

	return (
		<div className="channel-sidebar">
			<div className="channel-section">
				<div className="channel-section-title">Public</div>
				{publicChannels.map((ch) => (
					<SubscribedChannel
						key={ch}
						channel={ch}
						active={props.selectedChannel === ch}
						onSelect={() => props.onSelectChannel(ch)}
						onMessage={props.onMessage}
					/>
				))}
			</div>

			{userChannels.length > 0 && (
				<div className="channel-section">
					<div className="channel-section-title">User</div>
					{userChannels.map((ch) => (
						<SubscribedChannel
							key={ch}
							channel={ch}
							active={props.selectedChannel === ch}
							onSelect={() => props.onSelectChannel(ch)}
							onMessage={props.onMessage}
						/>
					))}
				</div>
			)}

			<div className="channel-section">
				<div className="channel-section-title">Groups</div>
				{availableGroups.map((group) => {
					const channel = `community.${group}`;
					const joined = joinedGroups.includes(group);

					if (joined) {
						return (
							<SubscribedChannel
								key={group}
								channel={channel}
								active={props.selectedChannel === channel}
								onSelect={() => props.onSelectChannel(channel)}
								onMessage={props.onMessage}
								action={{ label: "Leave", onClick: () => handleLeaveGroup(group) }}
							/>
						);
					}

					return (
						<div key={group} className="channel-item">
							<span className="channel-name" style={{ color: "#8b949e" }}>
								community.{group}
							</span>
							<button type="button" onClick={() => handleJoinGroup(group)}>
								Join
							</button>
						</div>
					);
				})}
			</div>
		</div>
	);
}
