// examples/chat-svelte/src/components/ConnectionPanel.svelte
<script lang="ts">
interface Props {
	wsUrl: string;
	token: string;
	connected: boolean;
	connectionState: string;
	onWsUrlChange: (url: string) => void;
	onTokenChange: (token: string) => void;
	onConnect: () => void;
	onDisconnect: () => void;
}

let { wsUrl, token, connected, connectionState, onWsUrlChange, onTokenChange, onConnect, onDisconnect }: Props = $props();
</script>

<div class="connection-bar">
	<input
		type="text"
		value={wsUrl}
		oninput={(e) => onWsUrlChange((e.target as HTMLInputElement).value)}
		placeholder="ws://localhost:3000/ws"
		disabled={connected}
	/>
	<textarea
		value={token}
		oninput={(e) => onTokenChange((e.target as HTMLTextAreaElement).value)}
		placeholder="Paste JWT token..."
		disabled={connected}
	></textarea>
	{#if connected}
		<button class="btn-disconnect" onclick={onDisconnect}>Disconnect</button>
		<div class="status-indicator">
			<span class="status-dot {connectionState}"></span>
			<span>{connectionState}</span>
		</div>
	{:else}
		<button class="btn-connect" disabled={!token} onclick={onConnect}>Connect</button>
	{/if}
</div>

// examples/chat-react/src/components/ConnectionPanel.tsx
import { useConnectionState } from "@sukko/react";

function StatusDot() {
	const { state } = useConnectionState();
	return (
		<div className="status-indicator">
			<span className={`status-dot ${state}`} />
			<span>{state}</span>
		</div>
	);
}

export function ConnectionPanel(props: {
	wsUrl: string;
	token: string;
	connected: boolean;
	onWsUrlChange: (url: string) => void;
	onTokenChange: (token: string) => void;
	onConnect: () => void;
	onDisconnect: () => void;
}) {
	return (
		<div className="connection-bar">
			<input
				type="text"
				value={props.wsUrl}
				onChange={(e) => props.onWsUrlChange(e.target.value)}
				placeholder="ws://localhost:3000/ws"
				disabled={props.connected}
			/>
			<textarea
				value={props.token}
				onChange={(e) => props.onTokenChange(e.target.value)}
				placeholder="Paste JWT token..."
				disabled={props.connected}
			/>
			{props.connected ? (
				<button type="button" className="btn-disconnect" onClick={props.onDisconnect}>
					Disconnect
				</button>
			) : (
				<button type="button" className="btn-connect" onClick={props.onConnect} disabled={!props.token}>
					Connect
				</button>
			)}
			{props.connected && <StatusDot />}
		</div>
	);
}
