// examples/chat-svelte/src/components/ConnectionPanel.svelte
<script lang="ts">
interface Props {
	wsUrl: string;
	token: string;
	connected: boolean;
	connectionState: string;
	onWsUrlChange: (url: string) => void;
	onTokenChange: (token: string) => void;
	onConnect: () => void;
	onDisconnect: () => void;
}

let { wsUrl, token, connected, connectionState, onWsUrlChange, onTokenChange, onConnect, onDisconnect }: Props = $props();
</script>

<div class="connection-bar">
	<input
		type="text"
		value={wsUrl}
		oninput={(e) => onWsUrlChange((e.target as HTMLInputElement).value)}
		placeholder="ws://localhost:3000/ws"
		disabled={connected}
	/>
	<textarea
		value={token}
		oninput={(e) => onTokenChange((e.target as HTMLTextAreaElement).value)}
		placeholder="Paste JWT token..."
		disabled={connected}
	></textarea>
	{#if connected}
		<button class="btn-disconnect" onclick={onDisconnect}>Disconnect</button>
		<div class="status-indicator">
			<span class="status-dot {connectionState}"></span>
			<span>{connectionState}</span>
		</div>
	{:else}
		<button class="btn-connect" disabled={!token} onclick={onConnect}>Connect</button>
	{/if}
</div>

// examples/chat-vue/src/components/ConnectionPanel.vue
<script setup lang="ts">
import StatusIndicator from "./StatusIndicator.vue";

const props = defineProps<{
	wsUrl: string;
	token: string;
	connected: boolean;
}>();

const emit = defineEmits<{
	"update:wsUrl": [url: string];
	"update:token": [token: string];
	connect: [];
	disconnect: [];
}>();
</script>

<template>
	<div class="connection-bar">
		<input
			type="text"
			:value="props.wsUrl"
			@input="emit('update:wsUrl', ($event.target as HTMLInputElement).value)"
			placeholder="ws://localhost:3000/ws"
			:disabled="props.connected"
		/>
		<textarea
			:value="props.token"
			@input="emit('update:token', ($event.target as HTMLTextAreaElement).value)"
			placeholder="Paste JWT token..."
			:disabled="props.connected"
		/>
		<button v-if="props.connected" class="btn-disconnect" @click="emit('disconnect')">
			Disconnect
		</button>
		<button v-else class="btn-connect" :disabled="!props.token" @click="emit('connect')">
			Connect
		</button>
		<StatusIndicator v-if="props.connected" />
	</div>
</template>
